### ISSUE TITLE
How to store attributes?

### ISSUE THREAD

**Issue by Swiftnesses** [snarky-snark/home-assistant-variables#10]
Hello,

I'm now on my way to 50 variables and would like to move some of the values to attributes (I use Node Red), is this a possibility? It would GREATLY reduce the number of variables I require.

Thanks in advance.

**Comment by Swiftnesses** [comment]
I know many people migrated over from: https://github.com/rogro82/hass-variables

Which had the option to do this.

**Comment by snarky-snark** [comment]
You can store any type of object in a variable. Try storing an array or dict in a variable to reduce the number of variables you have in use.

There are no plans to support generic variable attributes in this component at this time. The hass-variables component that you reference uses a dict to store attributes if I recall correctly.

**Comment by snarky-snark** [comment]
I should note that while any value can be stored in a var entity's state, Home Assistant appears to convert that value to a string before it is stored. See #48 for more information.
