### ISSUE TITLE
Integration error: var not found - maybe blocked HA 2023.6.3

### ISSUE THREAD

**Issue by Hubschra01** [snarky-snark/home-assistant-variables#101]
Hello,
after install Variables via HACS and i do a example entry:

`var:
  x:
    friendly_name: 'X'
    initial_value: 0
    icon: mdi:bug`

I got this Error.

![grafik](https://github.com/snarky-snark/home-assistant-variables/assets/40959322/f212beca-0af9-4433-93ba-a5aac8b65c96)

At the Log i found this:

`2023-06-25 14:34:52.637 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration variable which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
`
`2023-06-25 14:34:52.637 ERROR (SyncWorker_0) [homeassistant.loader] The custom integration 'variable' does not have a version key in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details`

My HA system is:

-  Home Assistant 2023.6.3 
- Supervisor 2023.06.2 
- Operating System 10.3 
- Frontend 20230608.0 - latest 

What can I do?

**Comment by snarky-snark** [comment]
What version of the var component are you using? This error should be fixed as of version 0.11.0.

**Comment by Hubschra01** [comment]
I use 0.15.0
![grafik](https://github.com/snarky-snark/home-assistant-variables/assets/40959322/48f49ccb-85cc-4073-9e1b-98442f2b3ef5)

**Comment by snarky-snark** [comment]
The `version` key is present in the manifest. Do you get this error with `0.15.1`?
https://github.com/snarky-snark/home-assistant-variables/blob/e99cac32a8b9577d1af6a0ab9dd485501952cc60/custom_components/var/manifest.json#L9
