### ISSUE TITLE
How to install in hassio VDI?

### ISSUE THREAD

**Issue by cableghost** [snarky-snark/home-assistant-variables#11]
If I do not have direct access to the folders in hassio VDI, how else may I install this? HACS also requires direct access to the file system.

**Comment by snarky-snark** [comment]
Sorry, I haven't experimented with a VDI deployment of HA, so I can only speculate. This custom component installs the same as any custom component for HA. Have you been able to install any other components besides this one?

**Comment by cableghost** [comment]
Pardon, not certain in this context what 'custom' is. I can install any of the add-on's available via repositories. As to adding via copying to directory, no, as I don't know how I could access the hassio file system.

**Comment by snarky-snark** [comment]
Custom components are third-party code for Home Assistant, but a separate concept from "add-ons" which I think are more closely maintained by HA. They are installed by placing the source code in `config/custom_components/` where `config/` is your home assistant config directory. Unfortunately, I can't find good documentation on this from Home Assistant. This is the best I can find at the moment: https://developers.home-assistant.io/docs/en/creating_component_loading.html

You should be able to place this variable component (or the HACS component) in your configuration directory. The question is where is that or how do you specify it when you start HA.

**Comment by cableghost** [comment]
Thank you. I'll post a thread on HA support to see if there's a way.

Edit: Discovered I can simply use vs code to copy files to.

**Comment by snarky-snark** [comment]
Cool! Glad you got it figured out.
