### ISSUE TITLE
Variable initial value will not update

### ISSUE THREAD

**Issue by tescophil** [snarky-snark/home-assistant-variables#110]
When a variable is first configured with an initial value. if a change is made to the initial value configuration and home assistant restarted the variable keeps the first initial value and ignore the new settings.

This is my config entrys

![Screenshot_2024-03-28-11-16-07-77_c3a231c25ed346e59462e84656a70e50](https://github.com/snarky-snark/home-assistant-variables/assets/59442445/06f220be-a5fb-4a37-b8f0-0172be2e7ba8)

and these are the actual values

![Screenshot_2024-03-28-11-38-42-44_c3a231c25ed346e59462e84656a70e50](https://github.com/snarky-snark/home-assistant-variables/assets/59442445/fa986344-05fc-4e9d-b5d5-dfb7ec9019e7)

Which don't match the values set in the config (apart from the standing charge variables which have not changed)

The values seen are the previous values when the variables where first used.

These variables are not updated or changed anywhere else, just a static value set in the config file.

**Comment by snarky-snark** [comment]
This is the expected behavior. Initial value is for the first time the variable entity is initialized on the home assistant database. If you want to reinitialize on startup, you need to hook the HA startup event.
