### ISSUE TITLE
HA 2024.7.2 has breaking changes 

### ISSUE THREAD

**Issue by PrayerfulDrop** [snarky-snark/home-assistant-variables#117]
With the latest update Variable does not start.  

Logger: homeassistant.helpers.translation
Source: helpers/translation.py:226
First occurred: 10:44:29 AM (2 occurrences)
Last logged: 10:44:29 AM

Failed to load integration for translation: Integration 'variable' not found.
Failed to load integration for translation: Integration 'icloud3' not found.

Logger: homeassistant.setup
Source: setup.py:271
First occurred: 10:44:31 AM (2 occurrences)
Last logged: 10:44:31 AM

Setup failed for 'variable': Integration not found.
Setup failed for 'icloud3': Integration not found.

Same issues with another 3rd party app: icloud3 - https://github.com/home-assistant/core/pull/121658

**Comment by hemaris-8b** [comment]
I would be thankful for continued maintenance of this integration - it seems to be the only global variable integration available for HA.

**Comment by snarky-snark** [comment]
I will fix this once I figure out what is wrong. Is there any more information in the logs that you could share?

**Comment by hemaris-8b** [comment]
> I would be thankful for continued maintenance of this integration - it seems to be the only global variable integration available for HA.

I wrote my earlier comment as I believed this integration was broken in HA 2024.7.2. Breaking changes section specifically mentioned "Variable" integration. 

Now I had more time, so I installed HA 2024.7.2 and in my system there were no issues. So the breaking changes notification seems to refer to another "Variable" integration.

**Comment by snarky-snark** [comment]
I see. This integration is named `var`. There is a different integration named `variable` that is the source of these log messages. 

https://github.com/rogro82/hass-variables
https://github.com/enkama/hass-variables
https://github.com/home-assistant/core/pull/121670
