### ISSUE TITLE
Feature request: store attributes

### ISSUE THREAD

**Issue by snarky-snark** [snarky-snark/home-assistant-variables#12]
A few people have requested the ability to store attributes alongside a variable. While a variable can store any kind of object including arrays or dicts, a separate parameter for attributes would allow for attributes to be stored and updated without complicating the logic for getting/setting the variable's value. Additionally, a separate parameter for attributes would remove the need to use a separate variable to store attributes for a another variable.

The approach I am considering is to add a new private `attributes` attribute to the variable that is a dict with corresponding `var.get_attr` and `var.set_attr` services to manipulate the attributes by key.

Attribute templates could then be added to allow for attributes to be updated whenever the variable's value updates. I envision attribute templates to be set via an `attributes_template` parameter that is a dict that maps attribute names to their templates.

At the moment, I don't have the cycles available to implement this feature properly, but I would happily consider pull requests from interested parties. This should be fairly straightforward to implement, if a bit tedious.

**Comment by jokerigno** [comment]
Hi, I moved to this component but I'm missing attributes too. 

Before using your solution I was using this 

https://diyfuturism.com/index.php/2017/12/15/useful-sensor-motion-last-seen-________/

Maybe can be useful to implement this function?

**Comment by Swiftnesses** [comment]
+1 for this!

**Comment by blizzrdof77** [comment]
+1

**Comment by snarky-snark** [comment]
This might be possible via the extra_state_attributes property.

https://developers.home-assistant.io/docs/core/entity#generic-properties

**Comment by snarky-snark** [comment]
Added in #71.
