### ISSUE TITLE
Can't install v9

### ISSUE THREAD

**Issue by NicoSomerwil** [snarky-snark/home-assistant-variables#15]
Hi there, like your integration, thanks! 
But I can't update from v8 to v9. Not with 0.103.0bx and not with 0.103.0 release.

**Comment by snarky-snark** [comment]
Are you installing via HACS? What happens when you try to install v0.9.0?

**Comment by ccorderod** [comment]
@snarky-snark the integration states: This repository version requires Home Assistant version 0.103.0
I am running 0.103.0.

**Comment by Bobbyiv** [comment]
I am also having trouble updating from V0.8.0 to V0.9.0. I tried uninstalling V0.8.0, rebooting, and re-installing V0.9.0. I updated from HASS.IO V0.102.3 to HASS.IO V0.103.0. I have attached screen shots, if it helps.
 

Running:
HASS.IO on Ubuntu 18.04.3 LTS.



![Screen Shot 2019-12-11 at 6 38 49 PM](https://user-images.githubusercontent.com/42158485/70670041-06776d80-1c46-11ea-9186-263e22e4c205.png)
![Screen Shot 2019-12-11 at 6 37 13 PM](https://user-images.githubusercontent.com/42158485/70670045-07a89a80-1c46-11ea-81f3-37be8db00016.png)

**Comment by snarky-snark** [comment]
Thanks for the report. This appears to be a bug in HACS. I'll back out the minimum HA version requirement until it is fixed.

**Comment by snarky-snark** [comment]
One thing to try is to ensure that your HACS installation is up-to-date.

**Comment by Bobbyiv** [comment]
I updated HACS yesterday to V0.18.1 when I still had HASS.IO V0.102.3 installed.

**Comment by Bobbyiv** [comment]
By the way, thanks for a get component. It has been a great addition.

**Comment by steve-gombos** [comment]
I was also seeing this issue running Hassio 0.103.0 on Ubuntu 18.04.  Upgrading directly from the vars page in HACS was throwing this error, but I also tried the "Upgrade All" button on the HACS Settings page and that worked.

**Comment by snarky-snark** [comment]
Release [v0.9.1](https://github.com/snarky-snark/home-assistant-variables/releases/tag/v0.9.1) is available which HACS should be able to install in HA 0.103.0.

Please let me know if this works for you all. Thanks!

@steve-gombos I'm surprised that worked! That sounds like it might be another bug in HACS, but glad you found a work-around.

**Comment by Bobbyiv** [comment]
@steve-gombos, I was not  aware there was an update all, in till now. Thanks for pointing that out. 

V0.9.1 had been released when I selected “Update All”. I will keep that in mind for next time as something to try. 

@snarky-snark, V0.9.1 updates with out any issue, HA load all my variables and all is working. 

Thank you for such fast and great support.
