### ISSUE TITLE
var.update fails

### ISSUE THREAD

**Issue by Bobbyiv** [snarky-snark/home-assistant-variables#16]
I use the var.update service in several automations to update time based variables. The automations have stopped work after updating Variable component to V0.9.1 last night. I try to preform var.update service under developer tools/services and received  this message "Failed to call service var/update. mappingproxy() argument must be a mapping, not All" . I uninstalled Variable component, reboot, and  reinstalled Variable component. I have attached a screen shot if it helps. 

System:
Home Assistant 0.103.0
Ubuntu 18.04.3 LTS
Variable 0.9.1
HACS 0.18.1

For a work around, I have changed my automations to use var.set, force_update. This seems to be working.

Thank you. 
![Screen Shot 2019-12-12 at 8 59 23 AM](https://user-images.githubusercontent.com/42158485/70721068-f8b3fd80-1cc2-11ea-83c1-a56d72fcf545.png)

**Comment by snarky-snark** [comment]
Thank you for the detailed report!

[v0.9.2](https://github.com/snarky-snark/home-assistant-variables/releases/tag/v0.9.2) should fix this.

**Comment by snarky-snark** [comment]
For the record, the `homeassistant.update_entity` service can be used to update any entity, including var entities.

**Comment by Bobbyiv** [comment]
@snarky-snark, I was not aware the homeassistant.update_entity update var entities, thank you.
