### ISSUE TITLE
Question: Is it possible use templating in tracked_entity_id

### ISSUE THREAD

**Issue by kraineff** [snarky-snark/home-assistant-variables#18]
Is it possible make "FOR LOOP" in tracked_entity_id?

**Comment by snarky-snark** [comment]
I'm not quite sure what you are asking. Can you give an example? The `tracked_entity_id` field determines which entities trigger an update to the variable when they have a state change event.

**Comment by kraineff** [comment]
I mean for example i need track all entities in group, but if I set group it only track group state, not entities! And for that I want to create an template that will add all entities from group to track!

**Comment by snarky-snark** [comment]
I see. As a workaround, you should be able to template `tracked_entity_id` in a call to `var.set` by using a `data_template` and passing a comma-separated list of entity ids.

Unfortunately, I'm not sure that it will work to pass a template in the var config.
