### ISSUE TITLE
Variable value restore not workin in v0.2.0

### ISSUE THREAD

**Issue by jacekpaszkowski** [snarky-snark/home-assistant-variables#2]
Hi,

aftere upgrading to version v0.2.0 restore function for all my variables stopped working.

After downgrade to  v0.1.0 all come back to work.

Regrads,
Jacek

**Comment by snarky-snark** [comment]
Thanks for the report. Do you mind sharing the config for one of these variables?

**Comment by snarky-snark** [comment]
@jacekpaszkowski, I haven't had time to try to reproduce your issue, but I think it may be fixed in release [v0.2.1](https://github.com/snarky-snark/home-assistant-variables/releases/tag/v0.2.1). Let me know if you have a chance to try it out.

**Comment by jacekpaszkowski** [comment]
@snarky-snark pretty straight forward setup :) eg. :

vacuum_power:
  friendly_name: 'Moc Roborock'

**Comment by jacekpaszkowski** [comment]
@snarky-snark v0.2.1 check and it work ok :) thx!
