### ISSUE TITLE
Initial_value not being picked up?

### ISSUE THREAD

**Issue by ijustlikeit** [snarky-snark/home-assistant-variables#20]
I used the initial_value in configuration.yaml and my understanding is upon startup this is supposed to set the variable to the value you specified.  Does not appear to do this; instead sets at 0 or 1?

**Comment by snarky-snark** [comment]
Post your config and version.

**Comment by ijustlikeit** [comment]
The config file--->

var:
security_armed:
     friendly_name: "Armed"
     initial_value: 'Armed'
     icon: mdi:alarm-bell
 security_disarmed:
     friendly_name: "Disarmed"
     initial_value: 'Disarmed'
     icon: mdi:bell-off

and the version is: Installed: v0.9.2

and the values assigned to security_armed and security_disarmed are (from states after reboot:)

var.security_armed | 0 | friendly_name: Armed icon: mdi:alarm-bell
-- | -- | --
var.security_disarmed | 1 | friendly_name: Disarmed icon: mdi:bell-off

**Comment by ijustlikeit** [comment]
I'm removing this var: integration for now, I have other ways of doing this.  Thanks.

**Comment by snarky-snark** [comment]
You might try NodeRed. It tends to be easier to manage for anything but the simplest variable configurations.
