### ISSUE TITLE
I can't get this to work

### ISSUE THREAD

**Issue by tjwally** [snarky-snark/home-assistant-variables#23]
in my config I got:
var:
  cpos:
    friendly_name: 'curtainsposition'
    initial_value: 30

in lovelace I got:
type: entities
entities:
  - entity: var.cpos

and it shows:
curtainsposition 0

 What am I doing wrong?

**Comment by snarky-snark** [comment]
Hmm. #20 seems to describe the same problem.

Just to confirm, you're not using that var in any automations are you?

**Comment by snarky-snark** [comment]
It's worth noting that `restore` is set to true by default. So if the var is ever set to another value, the initial value will be ignored.

Some things you can try:
- explicitly set `restore` to false and restart home assistant to try to get the initial value to be used
- go into developer tools and make a call to `var.set` to set it to 3.

**Comment by tjwally** [comment]
I'm currently only declaring the var in configuration.yaml and I want to update it trough scripts.
During testing this wasn't working and trough troubleshooting I figured out the var always returned 0.

I removed var.update from my script, reinstalled Variable trough hacs and now I only have the code posted in configure.yaml and lovelace.

When I set it to 3 in developer mode it works!
I'm trying restore false now and report back.

**Comment by tjwally** [comment]
restore: false made the initial value work!
I'm sorry already to report my next problem.. 
Updating the value in my scripts works like this:
    - service: var.set
      data:
       entity_id:
         - var.cpos
       value: 03

but when I try to use it in a delay like this, it doesn't work
    - delay:
            seconds: "{{ var.cpos | int }}"

I get:
UndefinedError: 'var' is undefined

**Comment by tjwally** [comment]
The var.set works but I can't read it back in the delay

**Comment by snarky-snark** [comment]
This page should have the information you need to get your templates working:
https://www.home-assistant.io/docs/configuration/templating/

In short,
```yaml
seconds: "{{ states('var.cpos') | int }}"
```

**Comment by tjwally** [comment]
Yes, right. I just figured that out after going trough https://www.home-assistant.io/docs/scripts/ again. Might be worth to point out in the documentation. For me it's hard to get this into my brain.
When it comes to variables I'm used to 
var = x
and then var is x

sorry.. I'm home assistant noob
