### ISSUE TITLE
Issue on HA 0.109

### ISSUE THREAD

**Issue by laguyle** [snarky-snark/home-assistant-variables#30]
Hello,

I just installed home-assistant-variables 0.9.3 on my HA version 0.109.6.
I just created a test variable on my configuration.yaml :

var:
  test:
    friendly_name: 'Test'
    initial_value: 20
    unit_of_measurement: °C

But when I check the config before restarting HA, I have the following error:

Invalid Configuration
Component error: var - cannot import name 'make_entity_service_schema' from 'homeassistant.helpers.config_validation' (/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/config_validation.py)

Can you please help ?
Thanks

**Comment by snarky-snark** [comment]
Strange, [make_entity_service_schema](https://github.com/home-assistant/core/blob/4d314ba4df7f0e797be80017a5643b05765f079f/homeassistant/helpers/config_validation.py#L790) is certainly defined there in 0.109.6.

Are you using hassio?

**Comment by laguyle** [comment]
No, I'm not.
HA is installed on my RPI in an virtual environment.

**Comment by snarky-snark** [comment]
Do you have any other custom components installed? Are you installing the var component manually?

My guess is that python is having trouble resolving that function because the PYTHONPATH doesn't contain the homeassistant sources or the custom_components directory is at the wrong location relative to the homeassistant sources.

I am running this component via HACS on Hassio, and there are no issues.

**Comment by laguyle** [comment]
Yes, I have other custom components.
And I'm using HACS too.

**Comment by snarky-snark** [comment]
Hm. Thanks for the report. I'm at a loss at the moment as to how this var custom component could be causing the problem. I imagine your other custom components perform similar imports.

If you're willing to disclose some of the other custom components you have installed, we could check to see if they do have similar imports to get a better idea of what's going wrong.

Other than that, I'm not sure how to approach this one. Apologies if you've done this already, but a good old-fashioned restart is always worth a try.

**Comment by laguyle** [comment]
Hello,
I'm using custom components "Attibutes" and "Disk Space".
I already made a restart without any success.

**Comment by laguyle** [comment]
The issue is solved.
I guess the last HA upgrade did not go as expected.
So all is good. :-)
Thanks

**Comment by snarky-snark** [comment]
Glad it worked out!
