### ISSUE TITLE
Add a popup when you click the variable entity in Lovelace to set the value of the variable

### ISSUE THREAD

**Issue by FutureTense** [snarky-snark/home-assistant-variables#31]
### Add a popup when you click the variable entity in Lovelace to set the value of the variable

I just *assumed* this functionality was already built-in, but if it is I couldn't find it.  And if it's not in here, it would be extremely helpful.  How else can an end-user set the value of a variable?

For example, I've been using a generic thermostat to store variables.  When I click on the thermostat in Lovelace, I get this:

![image](https://user-images.githubusercontent.com/7351283/83997517-931c9300-a92c-11ea-82d0-0a9922cbf953.png)

I can change the "temperature" to change my variable with the up/down arrows.  For this project, all you need is a simple textbox and ok/cancel buttons.  When the user clicks ok, you call the var.set service and pass in the value of the textbox.

**Comment by snarky-snark** [comment]
I think lovelace enhancements are outside of scope for this component. You can use various UI components like textinputs and buttons to achieve functionality like in your example.

For example, you can put a textinput and a script button in your lovelace config. When you click the script button, the script is triggered calling `var.set` using the value from the textinput.

I don't have time at the moment, but maybe someone on the discord group can walk you through it.

You can also set a variable value using the Developer Tools, either via the States tab or Services tab (`var.set`).
