### ISSUE TITLE
Allow setting variable value from Lovelace 

### ISSUE THREAD

**Issue by FutureTense** [snarky-snark/home-assistant-variables#32]
Is there a way to set the value of a variable from lovelace, similar to setting the value of an input_number?

**Comment by snarky-snark** [comment]
It depends on what you are trying to achieve. 

- A simple way to do this is to create a script that calls the `var.set` service to set the variable to whatever value is in the input_number textbox.

- Alternatively, you could set the variable to automatically update itself to the content of the input_number whenever the state of the input_number changes.

- If you don't care about having the control on your lovelace dashboard, you can set the state of the variable in the Developer Tools page either directly via the States tab or via the `var.set` service on the Services tab.

- You could also call the `var.set` service via an http request to your HA server. I forget the REST endpoint off-hand.

- You could also use NodeRed to call the `var.set` service.

There are no plans for the var component to support custom Lovelace UI for setting variables, so I think those are more or less your options.
