### ISSUE TITLE
Initialization failed

### ISSUE THREAD

**Issue by marclefevre** [snarky-snark/home-assistant-variables#35]
I have a new home assistant installation running on Ubuntu 20.04.  The version is 0.113.0.  I installed the variable integration using HACS and that seems to have been successful.  However, when I restart home assistant to complete the installation, the log shows the following error:

```
2020-07-27 08:24:04 ERROR (MainThread) [homeassistant.setup] Setup failed for var: Integration failed to initialize.
```
There is no other information.  The log does show:

```
2020-07-27 08:24:01 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for var which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
```
Where can I look for more information on what the failure is?  My logger component setup looks like this:

```
logger:
  default: info
  logs:
    homeassistant.core: info
```

**Comment by snarky-snark** [comment]
I don't believe there are any more useful log entries that can be enabled.

I would like to help you with this. Can you provide me with a little more information?
- Are you installing version 0.9.3 of the Variable integration?
- What does your configuration under `var` look like?
- Does the integration start successfully if you remove/comment all config related to `var` or if you create a simple config like
  ```
  var:
    x:
      initial_value: 0
  ```

**Comment by marclefevre** [comment]
Yes, I have version 0.9.3.

You've given me some direction on where to look and I tried a bunch of
configurations.  The bottom line is that the simple configuration of "x" in
the configuration.yaml file results in noi error.  However, If I move that
simple variable to an include yaml file, it fails.

So, for the failure, my configuration.yaml file looks like:
```
var: !include_dir_merge_list             config/variables
```

and my file in config/variables contains this:
```
x:
  initial_value: 0
```
Is there any reason why your integration won't support includes?

Marc

**Comment by snarky-snark** [comment]
Thanks, this is helpful.

Try adding a leading dash to each element of the list in the merge list files:
```
- x:
  initial_value: 0
```

It's not always clear from the [documentation](https://www.home-assistant.io/docs/configuration/splitting_configuration/#example-include_dir_merge_list) and nebulous error messages, but a yaml list is required in each file for `include_dir_merge_list` to work properly.

If that doesn't solve the problem, it will hopefully at least give us a better error message.

> Is there any reason why your integration won't support includes?

Config splitting is handled by core Home Assistant as far as I'm aware. Integrations don't have control over how it is handled.

**Comment by marclefevre** [comment]
I don't know about better...

Invalid config for [var]: expected a dictionary for dictionary value @
data['var']. Got [OrderedDict([('x', OrderedDict([('initial_value',
0)]))])]. (See /home/homeassistant/.homeassistant/configuration.yaml, line
82). Please check the docs at
https://github.com/snarky-snark/home-assistant-variables/blob/master/README.md


This is the result of

- x:
    initial_value: 0

in the included yaml file

**Comment by snarky-snark** [comment]
This looks like a more general HA configuration issue and not something specific to this var integration.

I would try skipping `include_dir_merge_list`, and including your var config directly in the same file. Then after you get that working, try to divide it into separate files.

YAML is sensitive to whitespace, so I'd make sure that your tabs and spaces are correct.

**Comment by marclefevre** [comment]
I put my variable definitions in a file in the same directory as configuration.yaml and used a simple !include to include it and that works.
