### ISSUE TITLE
Variables

### ISSUE THREAD

**Issue by OldFedor** [snarky-snark/home-assistant-variables#37]
How do I use the variable (0/1) in condition?
trigger:
condition: 
  - condition: ???
action:

Thank you for your response.
OldFedor, retiree.

**Comment by snarky-snark** [comment]
Try something like this, 
```
condition: template
value_template: "{{ states('var.example') == 1 }}"
action: ...
```

**Comment by OldFedor** [comment]
Thank you for your answer. But it doesn't work.

**Comment by snarky-snark** [comment]
The automation doesn't work? Do you get an error?

**Comment by snarky-snark** [comment]
Try this,
```
condition: state
    entity_id: var.example
    state: 1
```

**Comment by OldFedor** [comment]
The automatics didn't give out an error. 
The condition on the variable blocked execution. 
Now work. 
Thank you.

**Comment by OldFedor** [comment]
No, it still doesn't work.

#Ночник в гостиной
- alias: Гостиная-кнопка_вкл
  initial_state: true
  trigger:
  - platform: state
    entity_id: sensor.0x00158d00027a4d57_click
    to: 'single'
  condition:
  - condition: state
    entity_id: switch.sonoff_basic_relay
    state: 'off'
  - condition: state
    entity_id: var.bin_gost_do
    state: 0
  action:
  - service: switch.turn_on
    entity_id: switch.sonoff_basic_relay

**Comment by snarky-snark** [comment]
Can you go to "Developer Tools" and verify that the state of your variable is 0? You can also try setting the state to a different value and then back to 0 to see if that works.

Perhaps try to write to the system log as your only action. This will rule out the light as an issue. Additionally, comment all other conditions besides the variable condition. This will allow us to tell if the variable condition is the source of the problem.

```yaml
action:
      service: system_log.write
      data:
        message: 'light on!'
        level: info
```

**Comment by OldFedor** [comment]
Received a message from the server.
 Invalid config for [automation]: expected str for dictionary value @ data['condition'][1]['state']. Got None.

**Comment by snarky-snark** [comment]
That sounds like your variable has not been initialized. Can you go to "Developer Tools" on Home Assistant and check what the value of the variable is?

**Comment by OldFedor** [comment]
I set its value 0/1 from the button and output it to ui-lovelace. I can see the variable changing.

**Comment by OldFedor** [comment]
The variable is defined in configuration. yml as:
var:
  bin_gost_do:
    friendly_name: 'Освещение ниже порга'
    initial_value: 0
    icon: mdi:bug

**Comment by snarky-snark** [comment]
Make the state a string? 
`state: '0'`

**Comment by OldFedor** [comment]
Hooray! It's Working! 
Put as You said - a string. 
I appreciate your time. 
Your grandson also sends his regards.

**Comment by OldFedor** [comment]
My grandson

**Comment by snarky-snark** [comment]
I'm glad it worked!

**Comment by OldFedor** [comment]
Everything works as planned. The server still returns the same error. I only reloaded automation.

**Comment by OldFedor** [comment]
You are using a custom integration for var which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.

**Comment by OldFedor** [comment]
Experiments have shown that I wrote the code correctly. The most likely reason is that the mode (state) is not provided in your variable description.

**Comment by OldFedor** [comment]
I deleted everything. I use a timer as a variable. But this is not a solution, but a crutch.

**Comment by snarky-snark** [comment]
> You are using a custom integration for var which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.

This is an expected message, and does not necessarily indicate an error.

**Comment by snarky-snark** [comment]
> Experiments have shown that I wrote the code correctly. The most likely reason is that the mode (state) is not provided in your variable description.

Strange. Variables are entities and have state, so I'm not sure how this could be.
