### ISSUE TITLE
HACS not showing integration

### ISSUE THREAD

**Issue by joesilva101** [snarky-snark/home-assistant-variables#44]
I am trying to add your integration via HACS but it reports
![image](https://user-images.githubusercontent.com/77591188/104858502-bf9a8380-58ed-11eb-98f9-10880fb497e9.png)
checking https://hacs.xyz/docs/default_repositories and https://hacs-repositories.web.app/ it shows it listed there.
Is there somethings else that I need to do? is the issue something you can do or do I need to open a ticket in HACS?

Thank you

**Comment by snarky-snark** [comment]
The variable integration shows up for me in HACS version 1.10.0. Perhaps it's a connectivity issue?

**Comment by joesilva101** [comment]
that is the version that I have, just got it installed today. I have also cleared the cache... 
have tried it with both local connections as well as DNS, same result. if you have any other tips I would welcome them
does it show as a different name?
thank you

**Comment by snarky-snark** [comment]
![Screenshot_20210117-200553_Chrome](https://user-images.githubusercontent.com/1550707/104864715-70f5e500-58ff-11eb-8995-67a9f5d417d6.jpg)

**Comment by snarky-snark** [comment]
I'm not sure, but your suggestion of filing an issue with HACS is a good idea.

**Comment by joesilva101** [comment]
okay, I have figure it out...
on the initial setup of HACS I made the mistake of changing the filter for the country code...
I have put it back to "ALL" and I can now see your integration... thank you for your time
![image](https://user-images.githubusercontent.com/77591188/104868482-778d5800-5911-11eb-9855-02bb5b7232ab.png)

**Comment by snarky-snark** [comment]
Glad you got it sorted!
