### ISSUE TITLE
Can I use a binary_sensor

### ISSUE THREAD

**Issue by rlust** [snarky-snark/home-assistant-variables#45]
Can I use a binary sensor as an input to the tracked entities to count a variable?

**Comment by snarky-snark** [comment]
Yes, I think you should be able to accomplish that with a configuration like this:
```
value_template: "{{ (states('binary_sensor.name') }}" 
tracked_entity_id: binary_sensor.name
```

Does that work?

**Comment by snarky-snark** [comment]
Or are you trying to count how many times a binary sensor has been toggled?

```
value_template: "{{ (states('var.this_var') | int) + 1 }}" 
tracked_entity_id: binary_sensor.name
```
