### ISSUE TITLE
[Help required] How to set variable value from lovelace card button tap action

### ISSUE THREAD

**Issue by YvanLeTerrible** [snarky-snark/home-assistant-variables#46]
I want to assign a value (either typed manually , either prefined) to a variable with a tap_action action different the lovelace button of the variable (like a set or reset counter)
i can not find in the doc the syntax  of the yaml code of the button lovelace cards for feeding data to the var.set service

![var_set_lovelace_action](https://user-images.githubusercontent.com/68438044/105422588-44660400-5c44-11eb-82d6-2159e2325b99.PNG)

**Comment by YvanLeTerrible** [comment]
Drop it - i m so noob - i finally manage to do it  (for the restet part- yaml below)) - maybe you can document this somewhere

for the prompt for "typing input" of a value, i'm still searching (one button for+1, another for -1 ??)

type: button
entity: var.alarm_level
name: Alarme
show_state: true
hold_action:
  action: call-service
  service: var.set
  service_data:
    entity_id: var.alarm_level
    value: 0

![var_set_lovelace_hold_action](https://user-images.githubusercontent.com/68438044/105423752-6a8ca380-5c46-11eb-8272-fcf4ad71173f.PNG)

**Comment by snarky-snark** [comment]
Glad you got it working. You can use value templates to compute values like +1 or -1 when a button is clicked.
