### ISSUE TITLE
Can't set value template as state.attr

### ISSUE THREAD

**Issue by keecy** [snarky-snark/home-assistant-variables#47]
Hi,

I can use the var in an automation with for example:

 - value_template: "{{ states('sensor.heating') }}"
works, no problem 

but if change for
value_template: "{{ state.attr('sensor.heating','temperature') }}"

doesn't work..

maybe you can help?

Thanks,

**Comment by snarky-snark** [comment]
I think you want `state_attr` not `state.attr`.

**Comment by keecy** [comment]
Thanks a lot it is working like a charm

**Comment by snarky-snark** [comment]
Great!
