### ISSUE TITLE
Var.get service?

### ISSUE THREAD

**Issue by Swiftnesses** [snarky-snark/home-assistant-variables#5]
I currently use Node Red and another variable plugin, this allows me to get the value of a variable via a service (which I do in many NR flows), is this currently achievable?

**Comment by snarky-snark** [comment]
That seems simple enough to add. I'll see what I can do...

**Comment by snarky-snark** [comment]
In the meantime, I think you should be able to use a function like the one below to retrieve the state of a variable in Node Red. 

```
const globalHA = global.get('homeassistant');
msg.payload = globalHA.homeAssistant.states["var.foo"].state;
```

**Comment by snarky-snark** [comment]
@Swiftnesses, can you point me to the variable component that you are currently using? I would like to see how they are returning data from a service.

**Comment by Swiftnesses** [comment]
@snarky-snark here you go:

https://github.com/rogro82/hass-variables

**Comment by snarky-snark** [comment]
@Swiftnesses, that hass-variables component doesn't appear to have a service for getting the value of a variable.
My guess is that whatever you are doing in Node Red should work for this variable component as well.

**Comment by Swiftnesses** [comment]
Hmmm, a wrong assumption on my part then! I'll give it a shot later and let you know how I get on...

**Comment by snarky-snark** [comment]
@Swiftnesses, did you ever figure this out?

**Comment by Swiftnesses** [comment]
Yes, it works via Node Red's standard HA entity node - so it can be closed!
