### ISSUE TITLE
var entities using mySQL do not update with HA v.2021.05.*

### ISSUE THREAD

**Issue by ghost** [snarky-snark/home-assistant-variables#52]
Hello,
In the time of writing this text (HA version 2021.05.3) this text, my var config using SQL is not working. The **last working version of HA is 2021.4.6**. So I downgraded HA and all I need still works perfectly for me.

Please have a look on HA logs below + my HA config data.
Thanks for really great integration! 

## home-assistant.log
2021-05-13 08:34:03 ERROR (MainThread) [homeassistant.helpers.entity] Update for var.pv_pogoda fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 316, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 524, in async_device_update
    raise exc
  File "/config/custom_components/var/__init__.py", line 410, in async_update
    _LOGGER.debug("result = %s", res.items())
AttributeError: Could not locate column in row for column 'items'

## var definition
pv_moc_avg:
  friendly_name: Średnia moc PV  #średnia moc
  initial_value: 0
  icon: mdi:bug
  query: |
    SELECT entity_id, round(avg(CASE WHEN state > 0 THEN state ELSE 0 END),0) "srednia_moc" 
    FROM states 
    WHERE entity_id = "sensor.solarlog_power_ac" 
      AND convert_tz(last_changed,'utc','poland') >= now() - interval 30 minute 
    GROUP BY entity_id;
  column: "srednia_moc"
  unit_of_measurement: W
  value_template: >-
    {%- if states('sun.sun') == 'above_horizon' -%}
      {{ float(value)|round(0) }}
    {%else%}
      0
    {%endif%}

## System Health

version | core-2021.4.6
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
virtualenv | false
python_version | 3.8.7
os_name | Linux
os_version | 5.10.17-v7l+
arch | armv7l
timezone | Europe/Warsaw

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4882
Installed Version | 1.12.3
Stage | running
Available Repositories | 776
Installed Repositories | 4

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | May 20, 2021, 2:00 AM
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Lovelace</summary>

dashboards | 3
-- | --
resources | 2
views | 13
mode | storage

</details>

**Comment by snarky-snark** [comment]
Thanks for the report!

It appears HA made some database changes in its [May release](https://www.home-assistant.io/blog/2021/05/05/release-20215/#database-upgrades--performance).

I'm not immediately sure what is causing the problem, but this will be a good place to start.

**Comment by snarky-snark** [comment]
This appears to have been caused by a change to RowProxy (now Row) in sqlalchemy 1.4. The 2021.5.1 release of HA [upgraded sqlalchemy from 1.4.11 to 1.4.13](https://www.home-assistant.io/blog/2021/05/05/release-20215/#release-202151---may-7). 

https://docs.sqlalchemy.org/en/14/core/connections.html#sqlalchemy.engine.Row

I made some changes that should fix this. Why don't you give [v0.12.1](https://github.com/snarky-snark/home-assistant-variables/releases/tag/v0.12.1) a try on HA 2021.5.3, and see if it fixes your problem?

**Comment by ghost** [comment]
Thank you for your prompt help!

I do confirm variables **v.0.12.1 works perfectly with HA 2021.5.3**

*By chance I leaned that I cannot rely on version reported by HACS. After checking var/manifest file I understood I'm running very old version = **0.11.0**! Variables installed manually, then HA upgrade and... HACS started to report 0.12.2 is available.
Thanks once more.*

**Comment by snarky-snark** [comment]
Yeah, sorry, this may have been caused by my forgetting to update the var/manifest file to correspond to the release version used by hacs.

It should be accurate in v0.12.3.

**Comment by ghost** [comment]
I'm already on v0.12.3, all's excellent!
