### ISSUE TITLE
Trying to use variable in Lovelace template, as service_data, not standalone entity

### ISSUE THREAD

**Issue by iscofield** [snarky-snark/home-assistant-variables#55]
I have a lovelace button that calls a service and I am trying to utilize a variable that's been set and can't get it to actually populate the button.  I've tried every combination I can think of but nothing works.

This works in my configuration.yaml:
```
service: rest_command.turn_fan_light_on
data: 
  device: "{{ states('var.ian_fan') }}"
```

Populating the same in Lovelace does not.  I've tried all of the following combinations:
```
device: var.ian_fan
device: states.var.ian_fan
device: states.var.ian_fan.state
device: states('var.ian_fan')
device: "{{ states('var.ian_fan') }}"
device: "{{ states.var.ian_fan }}"
device: "{{ states.var.ian_fan.state }}"
```

If I put in the actual string that the variable represents, it works fine, so I know the surrounding context works, it would just appear that I can't use the variable in this manner?

**Comment by snarky-snark** [comment]
Have you tried using `data_template` instead of `data`?
