### ISSUE TITLE
Can not use 's1_f3' as entity_id

### ISSUE THREAD

**Issue by chinyaolin** [snarky-snark/home-assistant-variables#57]
Sorry for poor english.
When I use 'var.kolin_on_cool_s1_f3_t25' as entity_id, no matter what initial_value I set, It's not work!!
But 'var.kolin_on_cool_s1f3_t25' works fine.

**Comment by snarky-snark** [comment]
initial_value is only used on the first restart of HA unless restore is set to false. Could this be your issue?

**Comment by chinyaolin** [comment]
in configuration.yaml
> var: !include my_var.yaml

in my_var.yaml
> kolin_on_cool_s1f3_t25:       {initial_value: "JgCEABUzFBMWMx"}
> kolin_on_cool_s1f3_t26:       {initial_value: "JgCIAAAB"}
> kolin_on_cool_s1f3_t27:       {initial_value: "JgCIAAABJrEV"}

I can access thease vars and see them in /developer-tools/state
BUT, when I use entidy_id as below, states of 's1_f3' are empty
> kolin_on_cool_s1_f3_t25:       {initial_value: "JgCEABUzFBMWMx"}
> kolin_on_cool_s1_f3_t26:       {initial_value: "JgCIAAAB"}
> kolin_on_cool_s1_f3_t27:       {initial_value: "JgCIAAABJrEV"}

![image](https://user-images.githubusercontent.com/52078139/125881844-fa6075ca-b311-4c0f-8759-6d343f3614a8.png)

**Comment by snarky-snark** [comment]
Strange. As far as a I know, home assistant shouldn't treat those entities any differently, nor does the var component.
