### ISSUE TITLE
Feature Request: Reload component configuration

### ISSUE THREAD

**Issue by RoboMagus** [snarky-snark/home-assistant-variables#59]
Recently I found out that for some community components it is posible to reload the component configuration through HA server-controls without having to restart home assistant. 

That would be a great addition to this component as well!

**Comment by amrheing** [comment]
Hi guys, YES, that is what I also need to have :-)

Also a nice feature where the ability to store lists in the var.

kind regards, gerald

**Comment by RoboMagus** [comment]
@gertjanstulp, I noticed that you had some changes in your fork related to this.

Did you manage to get the reload implemented? 
If it work as expected could you please create a PR to get your changes merged into this repo for others to enjoy?

**Comment by snarky-snark** [comment]
Added in #69.
