### ISSUE TITLE
Should this work ?

### ISSUE THREAD

**Issue by IanAdd** [snarky-snark/home-assistant-variables#61]
```
var:
  ab_prev_booking:
        query: >
          SELECT attributes as attribs  FROM `states` WHERE 
          entity_id = 'calendar.airbnb'
          and left(last_changed,10)< left(now(),10)
          order by last_changed DESC limit 1;
        column: 'attribs'
        tracked_entity_id:
          - sensor.ab_booking_end_ts
```
I just get 'unknown' 
the query is valid and returns a long json string. 
Is there a length limit to a var ? 
I use mariadb, do I need to specify this? If so how?

**Comment by snarky-snark** [comment]
The length limit of a var is the same as the limit for any HA entity's state. The max length is 255 characters, if I recall correctly. Could that be the cause of your problem?

**Comment by IanAdd** [comment]
Thanks for responding, My curiosity was whether a 'var' variable had the same limit of 255 chars.
I have found a workaround using two entities and then contatenating them before parsing the json that it contained.
