### ISSUE TITLE
Log indicates var is undefined

### ISSUE THREAD

**Issue by davel4wa** [snarky-snark/home-assistant-variables#64]
I am using variables to store the states of two sensors I have created. For some reason using the sensor entities with the history_stats platform results in an error where the sensors are not found.
In any case I used a script to assign the sensor values to two variables. I did get that part to work after a few attempts. Using the variables within the history_stats platform worked great.
Now the bad news. I had been trying to build a variables folder in my config to eliminate having a lot of variables defined within the configuration file. I could not get that working so I commented out the !Include statement and added the var: entry along with the two variable definitions to the configuration file which worked fine. 
Since I got the two variables working correctly, I thought I would tackle the !include method again but gave up on it.
Subsequently I commented out the !include entry and pasted the var: statement back into the configuration file.
Now, even though the two variables exist in entities and have the correct values assigned, the target sensor now does not work and the HA log indicates that var is not defined.

Template variable error: 'var' is undefined when rendering '{{ now().replace(year = var.adjyear, month = var.adjmonth, day=1, hour=0, minute=0,second=0) }}'

Could it be that in HA restart the variables have not been assigned when the target sensor is being parsed?

**Comment by RoboMagus** [comment]
This is an old issue so I would hope you have this figured out by now.

If not, the error you're mentioning is indeed correct. `var`, much like `sensor` in that scope will be undefined in a template. Just like with accessing the state of a sensor (`{{ states('sensor.outdoor_temperature') }}`), you should use the correct access method. I.e. `{{ states('var.adjyear') }}`.
