### ISSUE TITLE
Min / Max Value for variable?

### ISSUE THREAD

**Issue by GunterAv** [snarky-snark/home-assistant-variables#66]
Hello,

is there a way to set a min/max value for a variable?

I want to run a condition in HA like:

alias: WZRolloManUp
description: ''
trigger: []
condition:
  - condition: numeric_state
    entity_id: var.rollo_wz_val
    above: '0'
    below: '95'
action:
  - service: script.wzrollomanup
    data: {}
mode: single

But it´s not working.

Can you help?

Best regard 
Gunter

**Comment by snarky-snark** [comment]
Could it be because you are using strings for your condition values? What happens if you try
```
above: 0
below: 95
```

**Comment by GunterAv** [comment]
Hello,

the same... even with the change it does not work.
The script is executed although the variable var.rollo_wz_val contains the value 0.
Also with "above: 1"

alias: WZRolloManup
description: ''
trigger: []
condition:
  - condition: numeric_state
    entity_id: var.rollo_wz_val
    above: 0
    below: 95
action:
  - service: script.wzrollomanup
    data: {}
mode: single

Best regards
Gunter

**Comment by snarky-snark** [comment]
Are you sure you are using `numeric_state` correctly? The docs show a different set of parameters for the action.

https://www.home-assistant.io/docs/automation/trigger/#numeric-state-trigger

I don't see any reason why it would be the var component, in particular, that is causing this to happen.

**Comment by GunterAv** [comment]
Hello,

i read the manual under:
[https://www.home-assistant.io/docs/scripts/conditions/](url)

Bets regards 
Gunter

**Comment by GunterAv** [comment]
Hello,

A short explanation what I want to achieve:
I want to execute a script only if the value of a variable is between 0 and 95, otherwise not.

How do I solve this?
Have I taken a wrong path?

Thanks and Best regards
Gunter

**Comment by snarky-snark** [comment]
Perhaps try using a trigger without the condition to narrow down the source of the problem. Or try using a sensor value instead of a var value. Again, I suspect this is not an issue with the var component, but you will have to debug further to determine that.

**Comment by GunterAv** [comment]
Hello,

the same :-(

alias: WZRolloManRUp
description: ''
trigger:
  - platform: numeric_state
    entity_id: var.rollo_wz_val
    above: 0
    below: 95
condition: []
action:
  - service: script.wzrollomanup
    data: {}
mode: single

Best regards
Gunter

**Comment by GunterAv** [comment]
Hello,

I have now solved it like this, and it works fine:

alias: WZRolloManUp
sequence:
  - variables:
      pos: '{{ (states(''var.rollo_wz_val'') | int) + 1 }}'
  - variables:
      pos1: >-
        {% if   pos <= 0  %} 0 {% elif pos >= 100 %} 100 {% else %} {{ pos  }}
        {% endif %}
  - service: motion_blinds.set_absolute_position
    data:
      absolute_position: '{{ pos1 }}'
    target:
      entity_id: cover.rollerblind_0001
  - service: var.set
    data:
      entity_id: var.rollo_wz_val
      value: '{{ pos1 }}'
mode: single
icon: mdi:archive-arrow-up

Best regards
Gunter
