### ISSUE TITLE
Question about configuration reload.

### ISSUE THREAD

**Issue by edautz** [snarky-snark/home-assistant-variables#67]
I am new to homeassistant and did install this variabeles packages. And implemented some variables. It workes fine and serves its purpose.

Question: Is there a way to define and change variables in the configuration.yaml file without reloading the complete homeassistant process? With other entities like sensors, automations etc, it is possible to reload those sections.

**Comment by RoboMagus** [comment]
Thats basically what is asked in issue #59.
Currently there is no support for that, but it is possible based on other custom components using that feature. So my hope is that it would be added at some point in the future.

**Comment by edautz** [comment]
Thanks. Would be great when that is  implemented.
