### ISSUE TITLE
Attributes support

### ISSUE THREAD

**Issue by RoboMagus** [snarky-snark/home-assistant-variables#71]
Hi Snarky,

First of all, thanks for porting the option to live reload the variable config in v0.13!

Some time back I've been toying with adding support for custom attributes to this component (see [my fork](https://github.com/RoboMagus/home-assistant-variables)).
I've come accros various use-cases where the HA built-in trigger- and state- based template sensors just don't cut it and this Var component fills in the gaps just fine. But what I am then missing is the ability to also set attributes for those entities. 

Would you be open to a PR for this addition?

**Comment by snarky-snark** [comment]
Hi @RoboMagus,

Support for variable attributes is one of the most frequently requested features for this component. I would be happy to consider a pull request for this.

I do prioritize backwards compatibility for this component. However, looking at your fork, that doesn't appear to be an issue.

Thanks!
