### ISSUE TITLE
`tracked_entity_id` stops updating the variable when hot-reloading the configuaration

### ISSUE THREAD

**Issue by zanna-37** [snarky-snark/home-assistant-variables#73]
When using `tracked_entity_id`, the variable stops updating if I hot-reload the integration (dev tools > YAML configuration reloading > variable).
The issue is fixed after a reboot.

```
var:
  test_var:
    restore: true
    value_template: >
      {% set entity='sensor.test' %}
      {% set self_ref='var.test_var' %}
      {% if states(entity) not in ['unavailable', 'unknown', 'none'] %}
        {{ states(entity) }}
      {% else %}
        {{ states(self_ref) }}
      {% endif %}
    tracked_entity_id:
      - sensor.test
```

**Comment by snarky-snark** [comment]
Thanks for the report!

The issue appears to be that variable event listeners are only being set on HA startup.

https://github.com/snarky-snark/home-assistant-variables/blob/99f8015ea8c275465254cd9b7d4f65f6d7020be1/custom_components/var/__init__.py#L301

**Comment by snarky-snark** [comment]
I think this is fixed now. Is it possible for you to update to the `develop` version of this component to see if it fixes your issue? Thanks!

**Comment by zanna-37** [comment]
Yes, thank you very much! Everything seems working now. Great job!
