### ISSUE TITLE
Setup fails in Home Assistant 2022.7.0b0

### ISSUE THREAD

**Issue by mabotze** [snarky-snark/home-assistant-variables#78]
Hi, after upgrading to the new beta of home assistant the var component seems to have an issue.

`The system cannot restart because the configuration is not valid: Package var setup failed. Component var cannot import name 'Events' from 'homeassistant.components.recorder.models' (/usr/src/homeassistant/homeassistant/components/recorder/models.py)`

**Comment by snarky-snark** [comment]
This should be fixed on the develop branch if you want to test.

**Comment by mabotze** [comment]
It works, thank you!
