### ISSUE TITLE
Restore, only restores state?

### ISSUE THREAD

**Issue by Swiftnesses** [snarky-snark/home-assistant-variables#8]
Howdy,

I have a number of variables that use icon templates. Upon reboot it appears only the state is restored and the custom icons are lost...? Shouldn't restore reinstate all associated values?

**Comment by snarky-snark** [comment]
Restore only restores entity state (value), not entity attributes like icon, friendly_name, etc. However, if you are specifying icon templates, they should be evaluated at HA startup. You will need to post your configuration for me to be able to say more.

**Comment by Swiftnesses** [comment]
That makes sense, I assumed would be the case...

I've noticed if I call the update service, things are fine. How long does it usually take after startup for HA to scan and update the entities?

**Comment by snarky-snark** [comment]
Templates are only evaluated when a variable updates. Updates only occur automatically when a tracked_event_type fires or a tracked_entity_id state change occurs. If neither of those parameters is specified, then the variable and its templates will not update automatically. You can use homeassistant_start event to update automatically on startup.

**Comment by Swiftnesses** [comment]
So here's the issue I'm trying to solve.

I have a variable like this:

```
home_occupied:
  friendly_name: "Home Occupied"
  value_template: >-
    {% if states('device_tracker.marks_iphone') == 'home' and states('device_tracker.linas_iphone') == 'home' %}
      true
    {% else %}
      false
    {% endif %}
  tracked_entity_id:
    -  device_tracker.marks_iphone
    -  device_tracker.linas_iphone
  restore: true
  icon_template: >-
    {% if states('device_tracker.marks_iphone') == 'home' and states('device_tracker.linas_iphone') == 'home' %}
      mdi:check-circle
    {% else %}
      mdi:close-circle
    {% endif %}
```

The variable updates great, the exception is, when I restart the state is restored, but the icon is not. Do you suggest I call the update service on HA startup to fix this?

**Comment by snarky-snark** [comment]
Add thw following to the config:
```yaml
tracked_event_type:
- homeassistant_start
```

That will force an update on start.

**Comment by Swiftnesses** [comment]
Sorted via HASS service calls, thank you!

A small quirk of Home Assistant, have you noticed that when you set a variable value of true or false (no quotes!), the state shows with a capital letter, i.e. True, False.

I need to use True or False in my if statements for template updates, weird!
