### ISSUE TITLE
Integration not loading

### ISSUE THREAD

**Issue by craggus2000** [snarky-snark/home-assistant-variables#84]
Hi,
I'm running latest version of HA, and downloaded and installed this custom integration via HACS, however it does not appear in the main integrations list to add. Subsequent custom integrations I have added do appear. I've restarted and refreshed, several times, and even left overnight, but it still does not appear.
Can you please assist?
Many thanks

**Comment by snarky-snark** [comment]
Sorry, I don't have a good idea why this would happen for this component, but not others. Which version of it did you install? Have you installed it before?
