### ISSUE TITLE
Variables in separate folder

### ISSUE THREAD

**Issue by davel4wa** [snarky-snark/home-assistant-variables#86]
When variables are moved into a separate folder, the var integration fails to initiate.

```
var: !include_dir_merge_list variables

```
HA container in Docker v. 2022.7.5

**Comment by snarky-snark** [comment]
~~Looks like the var component needs to set a unique ID. 
https://community.home-assistant.io/t/2021-4-for-our-advanced-users/297058/11~~

Edit: nevermind, this is wrong.

**Comment by snarky-snark** [comment]
I haven't found any documentation for this, yet.

**Comment by snarky-snark** [comment]
Okay I think this may be it:
https://developers.home-assistant.io/docs/config_entries_config_flow_handler#unique-ids

**Comment by snarky-snark** [comment]
The var integration doesn't use config flows, so this documentation doesn't help all that much.

**Comment by davel4wa** [comment]
https://github.com/home-assistant/core/pull/58596

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by snarky-snark** [comment]
That looks to be a unique_id for entities. I think that's different.

**Comment by davel4wa** [comment]
Described as being for the 'command line integration. '

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by snarky-snark** [comment]
> This adds unique_id as configuration variable to the command_line platform,
allowing to customize entities trough the UI.

This is a pull request to add a unique_id property to entities in the command_line integration. It does not add a unique ID to the integration itself.

**Comment by snarky-snark** [comment]
I don't think this is an issue with the var integration.

**Comment by snarky-snark** [comment]
Have you read #17? Is that your issue?

**Comment by davel4wa** [comment]
Well, don't I feel like a dumbass. That is exactly the problem. I built the variables folder by copying the var: definitions directly from the configuration file and neglected to format it as a list. I am not sure why because all of my other integration linked folders have the list construct. Sorry for wasting your time.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by snarky-snark** [comment]
No worries. It's a common issue! Glad you got it sorted.
