### ISSUE TITLE
Variable's updating

### ISSUE THREAD

**Issue by mindbuilder18** [snarky-snark/home-assistant-variables#87]
Hello im using the "Integration" to store values from my non smart devices Like the one that are IR-Remote controled. Up to now I only used the  var.set service and the value comand  to set a value to the variable. But now I want to Count the volume of a IR device and Up to now I was not able to code it in yaml. The var in named avvolume and i want to ad this counter comand to a script that increases or lowers the volume.

I hope it is understandeble what my problem is

**Comment by snarky-snark** [comment]
There are examples in the documentation in this repo. You can also try the Home Assistant community forums. This issue tracker is for reporting bugs and issues in the var component. Thanks.
