### ISSUE TITLE
Feature request: 'force_update' as an option?

### ISSUE THREAD

**Issue by Swiftnesses** [snarky-snark/home-assistant-variables#9]
Hello,

I've now transferred all 100+ of my variables over to this component, thank you!

I was wondering if it was possible to add a 'force_update' option, as is available on a few other components? I have a number of sensors that I need the value to update the chart for, regardless of if the value has changed, or not...

**Comment by snarky-snark** [comment]
I think this should be possible without too much work. I'll look into it when I have a chance.

**Comment by Swiftnesses** [comment]
Awesome, thank you. One of the features I used with my previous variable component was store attributes against a variable, is the currently possible?

**Comment by snarky-snark** [comment]
I'm not sure I follow, but custom attributes are not on the road map for this integration. You can always store a JSON object in a variable if you need to store multiple values. Please open a separate issue for each feature request.

**Comment by snarky-snark** [comment]
@Swiftnesses, I added support for `force_update` to the develop branch, but I am unable to test it at the moment. If you are able to test it and it works, then I will create a new release containing this feature.

If you have installed this integration via HACS, you can test the changes by selecting the develop version in HACS and restarting home assistant.

**Comment by snarky-snark** [comment]
@Swiftnesses, just curious if you ever tried out the develop branch with the `force_update` feature?

**Comment by snarky-snark** [comment]
Added in v0.8.0
