### ISSUE TITLE
Restore: true recorder dependency?

### ISSUE THREAD

**Issue by lloyda** [snarky-snark/home-assistant-variables#93]
Not really an issue, just a question.

If I have a variable with restore: true, does it rely on that variable being included in recorder?

**Comment by snarky-snark** [comment]
The variable entities use the same API for this as any generic Home Assistant entity. As a result, the answer should be the same for variables as they are for, say, input booleans.

That said, I think the answer is no. Restore state is saved separately from the HA database to my knowledge.
