### ISSUE TITLE
SQL returns 'unknown'

### ISSUE THREAD

**Issue by pdwonline** [snarky-snark/home-assistant-variables#95]
I used this to add  a simple SQL statement, but get 'unknown' as a result. I can see that something goes wrong, because the attribute last_update does not appear. Also I wonder how I could get this thing to update every minute..

``
db_sql:
  friendly_name: "db sql query"
  query: 'SELECT state_id FROM hass_db.states LIMIT 1;'
  column: 'state_id'
  attributes:
    last_update: '{{ now() }}'
  tracked_entity_id: 
    - sensor.db_connection
  restore: false

``

**Comment by snarky-snark** [comment]
Likely the same cause as #96.
