### ISSUE TITLE
Variable type changes and reboot

### ISSUE THREAD

**Issue by dominig** [snarky-snark/home-assistant-variables#97]
I am trying to use your variable integration and during my test and error in developing the correct template :-( I had to change the type of some of my variable from dictionary to a simple list.
To my surprise changing the variable type and init value in the config.yaml does not affect the existing variable. It remains unchanged.
How can I clean my old variables definition and restart on a clean sheet with a new version of my config.yaml ?

**Comment by snarky-snark** [comment]
You can clear your variable in the developer settings or set the restore attribute to false.
